// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Microsoft.Windows.Sdk
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.InteropServices;

    /// <summary>
    /// Represents a Win32 handle that can be closed with <see cref = "PInvoke.DestroyIcon"/>.
    /// </summary>
    internal class DestroyIconSafeHandle : SafeHandle
    {
        private static readonly IntPtr INVALID_HANDLE_VALUE = new IntPtr(-1);
        internal DestroyIconSafeHandle(): base(INVALID_HANDLE_VALUE, true)
        {
        }

        internal DestroyIconSafeHandle(IntPtr preexistingHandle, bool ownsHandle = true): base(INVALID_HANDLE_VALUE, ownsHandle)
        {
            this.SetHandle(preexistingHandle);
        }

        public override bool IsInvalid => this.handle == default(IntPtr) || this.handle == INVALID_HANDLE_VALUE;
        protected override bool ReleaseHandle() => PInvoke.DestroyIcon((HICON)this.handle);
    }
}