// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Microsoft.Windows.Sdk
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.InteropServices;

    internal partial struct OS_STRING
    {
        internal byte bLength;
        internal byte bDescriptorType;
        internal unsafe Span<ushort> MicrosoftString
        {
            get
            {
                fixed (void *p = &this.__MicrosoftString)
                    return new Span<ushort>(p, 7);
            }
        }

        [StructLayout(LayoutKind.Sequential, Pack = 1)]
        private struct __MicrosoftString_7
        {
            private ushort _1, _2, _3, _4, _5, _6, _7;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private __MicrosoftString_7 __MicrosoftString;
        internal byte bVendorCode;
        internal _Anonymous_e__Union Anonymous;
        [StructLayout(LayoutKind.Explicit)]
        internal partial struct _Anonymous_e__Union
        {
            [FieldOffset(0)]
            internal byte bPad;
            [FieldOffset(0)]
            internal byte bFlags;
        }
    }
}