// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Microsoft.Windows.Sdk
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.InteropServices;

    /// <content>
    /// Contains extern methods into "api-ms-win-shcore-scaling-l1-1-1.dll".
    /// </content>
    internal static partial class PInvoke
    {
        /// <inheritdoc cref = "GetDpiForMonitor(nint, MONITOR_DPI_TYPE, uint *, uint *)"/>
        internal static unsafe HRESULT GetDpiForMonitor(nint hmonitor, MONITOR_DPI_TYPE dpiType, out uint dpiX, out uint dpiY)
        {
            fixed (uint *dpiYLocal = &dpiY)
            {
                fixed (uint *dpiXLocal = &dpiX)
                {
                    return PInvoke.GetDpiForMonitor(hmonitor, dpiType, dpiXLocal, dpiYLocal);
                }
            }
        }

        /// <summary>Queries the dots per inch (dpi) of a display.</summary>
        /// <param name = "hmonitor">Handle of the monitor being queried.</param>
        /// <param name = "dpiType">The type of DPI being queried. Possible values are from the <a href = "https://docs.microsoft.com/windows/desktop/api/shellscalingapi/ne-shellscalingapi-monitor_dpi_type">MONITOR_DPI_TYPE</a> enumeration.</param>
        /// <param name = "dpiX">The value of the DPI along the X axis. This value always refers to the horizontal edge, even when the screen is rotated.</param>
        /// <param name = "dpiY">The value of the DPI along the Y axis. This value always refers to the vertical edge, even when the screen is rotated.</param>
        /// <returns>
        /// <para>This function returns one of the following values.</para>
        /// <para></para>
        /// <para>This doc was truncated.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//shellscalingapi/nf-shellscalingapi-getdpiformonitor">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("api-ms-win-shcore-scaling-l1-1-1", ExactSpelling = true)]
        internal static extern unsafe HRESULT GetDpiForMonitor(nint hmonitor, MONITOR_DPI_TYPE dpiType, [Out] uint *dpiX, [Out] uint *dpiY);
    }
}