// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Microsoft.Windows.Sdk
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.InteropServices;

    /// <content>
    /// Contains extern methods into "Gdi32.dll".
    /// </content>
    internal static partial class PInvoke
    {
        /// <summary>The DeleteObject function deletes a logical pen, brush, font, bitmap, region, or palette, freeing all system resources associated with the object. After the object is deleted, the specified handle is no longer valid.</summary>
        /// <param name = "ho">A handle to a logical pen, brush, font, bitmap, region, or palette.</param>
        /// <returns>
        /// <para>If the function succeeds, the return value is nonzero.</para>
        /// <para>If the specified handle is not valid or is currently selected into a DC, the return value is zero.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//wingdi/nf-wingdi-deleteobject">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("Gdi32", ExactSpelling = true)]
        internal static extern bool DeleteObject(IntPtr ho);
        /// <summary>The DeleteDC function deletes the specified device context (DC).</summary>
        /// <param name = "hdc">A handle to the device context.</param>
        /// <returns>
        /// <para>If the function succeeds, the return value is nonzero.</para>
        /// <para>If the function fails, the return value is zero.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//wingdi/nf-wingdi-deletedc">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("Gdi32", ExactSpelling = true)]
        internal static extern bool DeleteDC(HDC hdc);
    }
}