// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Microsoft.Windows.Sdk
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.InteropServices;

    /// <summary>The POINT structure defines the x- and y-coordinates of a point.</summary>
    /// <remarks>
    /// <para>The POINT structure is identical to the <a href = "https://docs.microsoft.com/windows/desktop/api/windef/ns-windef-pointl">POINTL</a> structure.</para>
    /// <para><see href = "https://docs.microsoft.com/windows/win32/api//windef/ns-windef-point#">Read more on docs.microsoft.com</see>.</para>
    /// </remarks>
    internal partial struct POINT
    {
        /// <summary>Specifies the <i>x</i>-coordinate of the point.</summary>
        internal int x;
        /// <summary>Specifies the <i>y</i>-coordinate of the point.</summary>
        internal int y;
    }
}