// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Microsoft.Windows.Sdk
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.InteropServices;

    /// <summary>The RECT structure defines a rectangle by the coordinates of its upper-left and lower-right corners.</summary>
    /// <remarks>
    /// <para>The RECT structure is identical to the <a href = "https://docs.microsoft.com/windows/desktop/api/windef/ns-windef-rectl">RECTL</a> structure.</para>
    /// <para><see href = "https://docs.microsoft.com/windows/win32/api//windef/ns-windef-rect#">Read more on docs.microsoft.com</see>.</para>
    /// </remarks>
    internal partial struct RECT
    {
        /// <summary>Specifies the <i>x</i>-coordinate of the upper-left corner of the rectangle.</summary>
        internal int left;
        /// <summary>Specifies the <i>y</i>-coordinate of the upper-left corner of the rectangle.</summary>
        internal int top;
        /// <summary>Specifies the <i>x</i>-coordinate of the lower-right corner of the rectangle.</summary>
        internal int right;
        /// <summary>Specifies the <i>y</i>-coordinate of the lower-right corner of the rectangle.</summary>
        internal int bottom;
    }
}