// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Microsoft.Windows.Sdk
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.InteropServices;

    /// <summary>The SIZE structure defines the width and height of a rectangle.</summary>
    /// <remarks>
    /// <para>The rectangle dimensions stored in this structure can correspond to viewport extents, window extents, text extents, bitmap dimensions, or the aspect-ratio filter for some extended functions.</para>
    /// <para><see href = "https://docs.microsoft.com/windows/win32/api//windef/ns-windef-size#">Read more on docs.microsoft.com</see>.</para>
    /// </remarks>
    internal partial struct SIZE
    {
        /// <summary>Specifies the rectangle's width. The units depend on which function uses this structure.</summary>
        internal int cx;
        /// <summary>Specifies the rectangle's height. The units depend on which function uses this structure.</summary>
        internal int cy;
    }
}