namespace WinUIEx.MediaPlayer
{
    [default_interface]
    runtimeclass MediaPlayerElement : Microsoft.UI.Xaml.Controls.Control
    {
        MediaPlayerElement();

        static Microsoft.UI.Xaml.DependencyProperty SourceProperty { get; };
        Windows.Foundation.Uri Source;
        
        Boolean AutoPlay;
        static Microsoft.UI.Xaml.DependencyProperty AutoPlayProperty{ get; };

        Windows.Media.Playback.MediaPlayer MediaPlayer { get; };

        Microsoft.UI.Xaml.Media.ImageSource PosterSource;
        static Microsoft.UI.Xaml.DependencyProperty PosterSourceProperty{ get; };

        Microsoft.UI.Xaml.Media.Stretch Stretch;
        static Microsoft.UI.Xaml.DependencyProperty StretchProperty{ get; };

        // bool IsFullWindow;
        // bool AreTransportControlsEnabled;
        // MediaTransportControls TransportControls;
        // void SetMediaPlayer(MediaPlayer mediaPlayer);
    }
}
