#pragma once
#include <unknwn.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Microsoft.UI.Composition.h>
#include <winrt/Microsoft.UI.Xaml.h>
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#include <winrt/Microsoft.UI.Xaml.Data.h>
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#include <winrt/Microsoft.UI.Xaml.Navigation.h>
#include <winrt/Microsoft.UI.Dispatching.h>
#include <wil/cppwinrt_helpers.h>
#include <winrt/Windows.UI.Xaml.Interop.h>

#include <winrt/Windows.Media.Playback.h>
#include <Microsoft.UI.Xaml.media.dxinterop.h>
//#include <DXGI1_2.h>
#include <Dxgi1_3.h>
#include <D3D11.h>
#include <D2d1_1.h>
#include <windows.graphics.directx.direct3d11.interop.h>
