name: Publish WinUIEx NuGet

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: windows-2022
    
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4
    
    - name: Setup Visual Studio Command Prompt
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        msbuild /restore /t:Build src/WinUIEx/WinUIEx.csproj /p:Configuration=Release


    - name: Pack
      run: |
        msbuild /t:Pack src/WinUIEx/WinUIEx.csproj /p:Configuration=Release /p:NoBuild=true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Packages
        path: artifacts/NuGet/Release 

    # Get a short-lived NuGet API key
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
   
    - name: Push to NuGet
      run: |
        dotnet nuget push artifacts\NuGet\Release\*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
